#!/usr/bin/env python3
# -*- coding:utf-8 -*-

from polychromatic.profiles import AppProfiles
import openrazer.client as rclient
from sys import argv

class ChangeProfile(AppProfiles):
	def change(self, uuid):
		devman = rclient.DeviceManager()		
		device = devman.devices[0];	
		self.send_profile_from_file(device, uuid)
		
cp = ChangeProfile()
cp.change(argv[1])
